### ISSUE TITLE
Reduce the time cost from txt file to lab file

### ISSUE THREAD

**Issue by wblgers** [ZackHodari/tts_data_tools#1]
Hi,
Seems you are doing some front end process job for tts in this project, I have some questions about it.
Now I'm using Merlin to do English speech synthesis deploy, I follow the script "prepare_labels_from_txt.sh" to convert raw text into the .lab file, and I see you are trying to translate the shell script into python script, and also call "festival".

And my problem is, the time cost in frontend is very long, even compared with all the post process (duration model predict, acoustic model predict, and world vocoder wave generating). 
For example, for one sentence "Can I help you?", the frontend part cost 900ms, the other part cost 120ms.
How can I reduce the time cost in frontend based on festival, I'll be appreciate if you reply me and give me some suggestions. 

Bolong.Wen

**Comment by ZackHodari** [comment]
Festival is not intended as a commercial tool, it is designed for academic research and as such is not optimised for speed.

The issue you are having for synthesising one sentence may be related to the startup time of Festival, try generating for many sentences in batch mode and see if the average speed is better. If so you could try running Festival in server mode, this would remove all the setup time.

If it is still too slow you could take a look at Flite (stripped down version of Festival written only in C) which is designed to be very fast
http://www.festvox.org/flite/

Other than this your best option is to look into other tools or write your own frontend, though this would be a substantial amount of work.
https://synsig.org/index.php/Software
https://github.com/CSTR-Edinburgh/Ossian
http://mary.dfki.de

**Comment by wblgers** [comment]
Hi,
Thanks for your suggestions, I'll try Flite firstly.
