### ISSUE TITLE
Could you please offer some examples?

### ISSUE THREAD

**Issue by Yablon** [ZackHodari/tts_data_tools#2]
Hello, could you please offer some exapmles, showing that how I can extract what from what ?
Thank you !

**Comment by ZackHodari** [comment]
If you want to extract Merlin-equivalent labels take a look at the [process_dataset.py](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/scripts/process_dataset.py) script. It basically called [lab_to_feat.py](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/lab_gen/lab_to_feat.py) and [world_with_reaper_f0.py](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/wav_gen/world_with_reaper_f0.py), matches the length number of frames in the durations with the acoustic features, and trims silences (if requested). 

The project is written with the intention that some people can use the provided scripts out of the box. But if you need more custom feature extraction the idea is that you can write your own script (e.g. [extract phone identity](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/scripts/process_phones.py)).

Label creation scripts are found in  [lab_gen/](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/lab_gen) and have the following functionalities:
- Extract Utterance structures using Festival
- Convert Festival Utterance structures to flat HTS-style full-context labels
- Perform forced-alignment using HTK
- Extract phone-level one-hot, binary, and positional features according to a [question file](https://github.com/ZackHodari/tts_data_tools/tree/master/tts_data_tools/resources/question_sets)
- Extract frame-level [counter features](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/lab_gen/lab_to_feat.py#L244-L422)

Waveform feature extraction scripts can be found in  [wav_gen/](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/wav_gen), the script [world_with_reaper_f0.py](https://github.com/ZackHodari/tts_data_tools/blob/master/tts_data_tools/wav_gen/world_with_reaper_f0.py) does the following:
- Extracts F0 with [REAPER](https://github.com/google/REAPER)
- Extracts the smoothed spectrogram and band aperiodicity with [WORLD](https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder)
- Converts the smoothed spectrogram and band aperiodicity to Mel-scale using [pySPTK](https://github.com/r9y9/pysptk)

Take a look at the [README](https://github.com/ZackHodari/tts_data_tools/blob/master/README.md) for more details.

**Comment by Yablon** [comment]
@ZackHodari Thanks !
